name: QA Pipeline

# on:
#   schedule:
#     - cron: '57 01 01 02 *'  # Scheduled for February 1, 2025, at 1:28 AM UTC

on:
  schedule:
    # Schedule to run at 1:06 AM UTC daily
    - cron: '9 1 * * *'  




  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.16'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        google-chrome --version
        python -m pip install --upgrade pip
        pip install behave
        pip install -r requirements.txt

    - name: Run Behave tests
      run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' behave features --tags=@Smoke12345
